### ISSUE TITLE
Implement tensor board (logging + plotting)

### ISSUE THREAD

**Issue by spasojevic96** [Llewe/Autonome-Systeme-Praktikum#20]

**Comment by spasojevic96** [comment]
logging + plotting in one

**Comment by Llewe** [comment]
I think it would be good to store the logs like: `.\logs\<env-name>\<name of the run>\events.out.tfevents.<timeInSec>.<pcname>`.
Maybe check with tensorboard if they suggest anything else.

Docs for tensorboard with pyTorch
https://pytorch.org/tutorials/recipes/recipes/tensorboard_with_pytorch.html
